#!/usr/bin/python3

"""
A client for communicating with a server in a virtual world

The URLs generated by the server are temporary

"""

import requests


def send(url, parameters):
    # sending data as params makes it easier to parse on the LSL end
    r = requests.get(url, params=parameters)
    # r = requests.post(url, data=parameters)
    print(r.url)
    print(r)
    print(r.text)


if __name__ == "__main__":

    url = ''
    parameters = {'cmd': 'move', 'x': '+1', 'y': '-3', 'z': '0'}
    send(url, parameters)


